MACRO(ADD_SUBDIRS)
  FILE(GLOB sub_dirs RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} *)
  FOREACH(dir IN LISTS sub_dirs)
    IF (IS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/${dir})
      IF (EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${dir}/CMakeLists.txt)
        add_subdirectory(${dir})
      ENDIF()
    ENDIF()
  ENDFOREACH()
ENDMACRO()


MACRO(ADD_TEST)
  FILE(GLOB file_list "${CMAKE_CURRENT_SOURCE_DIR}/test_*.cpp")
  FOREACH(fname IN LISTS file_list)
    get_filename_component(basename ${fname} NAME_WE)
    add_executable(${module_name}_${basename} ${fname})
    target_link_libraries(${module_name}_${basename} ${LIBRARIES} ${EXTERNAL_LIBS})
  ENDFOREACH()
ENDMACRO()


MACRO(ADD_LIB)
  FILE(GLOB file_list "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")
  if (file_list)
    add_library(${module_name} ${file_list})
    set(LIBRARIES ${LIBRARIES} ${module_name} CACHE INTERNAL "")
    # message("${module_name} : ${file_list}")
  endif()
ENDMACRO()

